const fs=require('fs'),vm=require('vm'),assert=require('assert');
const box={AbortSignal,console,importScripts(){},chrome:{runtime:{onInstalled:{addListener(){}},onMessage:{addListener(){}}}},fetch:null};
vm.createContext(box);vm.runInContext(fs.readFileSync(__dirname+'/background/service-worker.js','utf8'),box);
async function run(){
 assert.ok(box.extractSalary('工资：60 红包日结！（工作4个小时）').includes('60'));
 assert.equal(box.extractSalary('9月13号，下午4点到8点，工资面议'),'');
 assert.equal((await box.highlightRisks(null,[])).empty,true);
 let pay=await box.planQuestions('工资：60 红包日结',[],[{key:'salary'},{key:'settlement'}],{},{});
 assert.equal(pay.items.length,0);
 const missing=[{key:'company'},{key:'fee'}];
 const turns=[{answers:[{key:'company',question:'公司名称？',answer:'已确认'}]}];
 let r=await box.planQuestions('配送工作',turns,missing,{},{});
 assert.deepEqual(Array.from(r.items,i=>i.key),['fee']);
 box.fetch=async()=>({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({questions:[{key:'company',question:'站点是谁？'},{key:'fee',question:'押金多少？'},{key:'fee',question:'需要押金吗？'}]})}}]})});
 r=await box.planQuestions('配送工作',turns,missing,{}, {enableApi:true,apiKey:'test'});
 assert.deepEqual(Array.from(r.items,i=>i.key),['fee']);
 box.fetch=async()=>({ok:true,json:async()=>({choices:[{message:{content:'{"questions":[]}'}}]})});
 r=await box.planQuestions('配送工作',[],missing,{}, {enableApi:true,apiKey:'test'});assert.equal(r.items.length,0);
 box.fetch=async()=>{throw Error('simulated offline')};
 r=await box.planQuestions('配送工作',turns,missing,{}, {enableApi:true,apiKey:'test'});assert.equal(r.source,'local-fallback');assert.equal(r.items.length,1);
 box.getSettings=async()=>({});box.getEnabledRules=async()=>[];
 box.riskScan=()=>({riskLevel:'低风险',score:0});box.extractInfo=async()=>({});box.getMissingFields=()=>missing;
 box.buildFinalReport=async()=>({agentSummary:'报告'});box.saveHistory=async()=>{};
 let calls=0;box.planQuestions=async()=>{calls++;return {questions:['测试'],items:[],source:'local'}};
 await box.analyzeText('招聘','',{forceReport:true});assert.equal(calls,0);
 await box.analyzeText('招聘','',{turns:[turns[0],turns[0],turns[0]]});assert.equal(calls,0);
 const result=await box.analyzeText('招聘','',{});assert.equal(result.needQuestion,true);
 console.log('PASS: answered-topic exclusion, deduplication, empty completion, API fallback, manual stop, 3-round limit, initial questions');
}run().catch(e=>{console.error(e);process.exitCode=1});
